site_name: Open Source Development 2023/2
repo_url: https://github.com/insper/open-dev/
repo_name: Open Dev
site_url: https://insper.github.io/open-dev/

theme:
    name: 'material'

extra_css:
  - css/custom.css
  - css/people.css

nav:
  - 'Home': 'index.md'
  - 'syllabus.md'
  - 'assessment.md'
  - 'students.md'
    # - 'Agenda apresentações': 'agenda_apresentacoes.md'
  - 'Lessons':
    - 'lessons/01-distributed-workflow/index.md'
      # - 'aulas/02-comunidades-de-software/index.md'
      # - 'aulas/03-documentacao-de-software/index.md'
      # - 'aulas/04-discussao-documentacao-de-software/index.md'
      # - 'aulas/05-projeto-profissional/index.md'
      # - 'aulas/06-distribuicao-software/index.md'
      # - 'aulas/07-localizacao/index.md'
      # - 'aulas/08-testes-automatizados/index_2022.md'
      # - 'aulas/09-licencas/index.md'
      # - 'aulas/09-cultura-livre/index.md'
      # - 'aulas/10-minha-primeira-contribuicao/index.md'
#    - 'aulas/11-contribuicoes-externas/index.md'
  - 'Impact': 
    - '2023/2': 'impact.md'
    - '2022/2': 'impact-2022.md'
    - '2021/2': 'impact-2021.md'
    - '2020/1': 'impact-2020.md'
    - '2019/2': 'impact-2019.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: 
  - git-revision-date-localized
