site_name: Desenvolvimento Aberto 2021/2
repo_url: https://github.com/insper/dev-aberto/

theme:
    name: 'material'

extra_css:
  - css/custom.css

nav:
  - 'Home': 'index.md'
  - 'burocracias.md'
  - 'Skills e avaliação': 'regras.md'
  - 'Alunos': 'alunos.md'
  - 'Impacto': 
    - '2021/2': 'impacto.md'
    - '2020/1': 'impacto-2020.md'
    - '2019/2': 'impacto-2019.md'

markdown_extensions:
  - attr_list
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist
  - pymdownx.details
  - material_icons